export const charadesDeck: string[] = [
  // Actions
  "Brushing teeth",
  "Tying shoelaces",
  "Driving a car",
  "Taking a selfie",
  "Flipping a pancake",
  "Walking a dog",
  "Shoveling snow",
  "Putting on makeup",
  "Jumping rope",
  "Flying a kite",
  // Sports & Hobbies
  "Bowling",
  "Shooting a basketball",
  "Serving in tennis",
  "Weightlifting",
  "Playing guitar",
  "Swimming",
  "Casting a fishing rod",
  "Boxing",
  "Ice skating",
  "Surfing",
  // Animals
  "Elephant",
  "Gorilla beating its chest",
  "Snake",
  "Chicken",
  "Kangaroo",
  "Giraffe",
  "Penguin",
  "Shark",
  "T-Rex",
  "Bull charging",
  // Famous People / Characters
  "Spider-Man",
  "Harry Potter",
  "Michael Jackson",
  "The Hulk",
  "Superman",
  "Darth Vader",
  "Elvis Presley",
  "Usain Bolt",
  "Batman",
  "Beyonce",
  // Situations
  "Riding a roller coaster",
  "Blowing out birthday candles",
  "Opening a present",
  "Eating spaghetti",
  "Hula hooping",
  "Ironing clothes",
  "Archery",
  "Brushing hair",
  "Vacuuming",
  "Arm wrestling",
];
