export const mostLikelyToDeck: string[] = [
  "Most likely to forget someone's name two seconds after hearing it",
  "Most likely to laugh at the worst possible moment",
  "Most likely to survive a zombie apocalypse",
  "Most likely to accidentally send a text to the wrong person",
  "Most likely to become famous",
  "Most likely to cry during a movie",
  "Most likely to eat something off the floor",
  "Most likely to show up late to their own wedding",
  "Most likely to start an argument over something silly",
  "Most likely to fall asleep anywhere",
  "Most likely to binge an entire TV series in one sitting",
  "Most likely to get lost in their own neighborhood",
  "Most likely to become a millionaire",
  "Most likely to talk their way out of a speeding ticket",
  "Most likely to still use a flip phone in 2030",
  "Most likely to go viral on social media by accident",
  "Most likely to adopt 10 cats",
  "Most likely to say something embarrassing in front of a crowd",
  "Most likely to win a cooking competition",
  "Most likely to forget their own birthday",
  "Most likely to get into a fight with a vending machine",
  "Most likely to become a reality TV star",
  "Most likely to trip over nothing on a flat surface",
  "Most likely to secretly google something mid-conversation",
  "Most likely to get caught talking to themselves",
  "Most likely to leave the house with mismatched shoes",
  "Most likely to befriend a stranger on a flight",
  "Most likely to eat the last slice without asking",
  "Most likely to cry over a cute animal video",
  "Most likely to lock themselves out of the house",
  "Most likely to write a bestselling book",
  "Most likely to get scared by their own reflection",
  "Most likely to dramatically retell a boring story",
  "Most likely to have a secret talent nobody knows about",
  "Most likely to accidentally like a photo from 3 years ago while stalking someone",
  "Most likely to burn water while trying to cook",
  "Most likely to give the best advice but never follow it themselves",
  "Most likely to quote a movie in every conversation",
  "Most likely to win a staring contest",
  "Most likely to survive on instant noodles for a month",
  "Most likely to ask for directions and then ignore them",
  "Most likely to overdress for a casual hangout",
  "Most likely to bring a suitcase for a one-night trip",
  "Most likely to start a business before turning 30",
  "Most likely to still not know how to fold a fitted sheet",
  "Most likely to ugly cry in public",
  "Most likely to take 100 selfies and post none",
  "Most likely to get caught singing in the shower",
  "Most likely to secretly eat dessert before dinner",
  "Most likely to still believe in a childhood superstition",
];
