export const truthOrDareDeck: string[] = [
  "TRUTH: What is the most embarrassing thing that has happened to you in public?",
  "DARE: Do your best impression of someone in the room",
  "TRUTH: What is the last lie you told?",
  "DARE: Let the group go through your phone's camera roll for 30 seconds",
  "TRUTH: What is your most irrational fear?",
  "DARE: Speak in an accent for the next three rounds",
  "TRUTH: What is the weirdest thing you have ever eaten?",
  "DARE: Do 10 push-ups right now",
  "TRUTH: Who in this room would you want on your team during an apocalypse?",
  "DARE: Let someone in the group send one text from your phone",
  "TRUTH: What is the longest you have gone without showering?",
  "DARE: Talk without closing your mouth for the next 30 seconds",
  "TRUTH: What is the most childish thing you still do?",
  "DARE: Hold an ice cube in your hand until it melts",
  "TRUTH: Have you ever pretended to like a gift you actually hated?",
  "DARE: Do your best dance move right now",
  "TRUTH: What is the most useless talent you have?",
  "DARE: Sing the chorus of the last song you listened to",
  "TRUTH: What is something you have never told anyone in this room?",
  "DARE: Let the group choose a new profile picture for you",
  "TRUTH: What was your worst haircut ever?",
  "DARE: Keep a straight face while everyone tries to make you laugh for 30 seconds",
  "TRUTH: What is your guilty pleasure TV show or movie?",
  "DARE: Eat a spoonful of a condiment chosen by the group",
  "TRUTH: What is the most trouble you have ever been in?",
  "DARE: Post the oldest selfie on your phone to your social media story",
  "TRUTH: Who was your first crush?",
  "DARE: Speak in only questions for the next two rounds",
  "TRUTH: What is the pettiest reason you stopped talking to someone?",
  "DARE: Let the person to your right draw something on your arm with a pen",
  "TRUTH: What is the worst advice you have ever given?",
  "DARE: Do a dramatic reading of the last text you sent",
  "TRUTH: Have you ever blamed someone else for something you did?",
  "DARE: Walk like a crab for the next minute",
  "TRUTH: What is the most money you have wasted on something stupid?",
  "DARE: Call a friend and sing happy birthday to them regardless of the date",
  "TRUTH: What is something you pretend to understand but actually do not?",
  "DARE: Let the group style your hair however they want",
  "TRUTH: What is the strangest dream you have ever had?",
  "DARE: Do a dramatic slow-motion replay of the last thing you did",
  "TRUTH: Who in this room do you think would be the worst roommate?",
  "DARE: Try to juggle three random objects from the room",
  "TRUTH: What is a secret skill or hobby you have never mentioned?",
  "DARE: Balance a book on your head for the next round",
  "TRUTH: What is the most embarrassing thing in your search history?",
  "DARE: Say a tongue twister five times fast without messing up",
  "TRUTH: Have you ever eavesdropped on a conversation and gotten caught?",
  "DARE: Do your best animal impression and let the group guess the animal",
  "TRUTH: What is the biggest misconception people have about you?",
  "DARE: Wear your shirt inside out for the rest of the game",
];
