export const twoTruthsOneLieDeck: string[] = [
  "Tell two truths and a lie about your childhood",
  "Tell two truths and a lie about your food preferences",
  "Tell two truths and a lie about places you have traveled to",
  "Tell two truths and a lie about your school days",
  "Tell two truths and a lie about your hidden talents",
  "Tell two truths and a lie about your family",
  "Tell two truths and a lie about your worst habits",
  "Tell two truths and a lie about things that scare you",
  "Tell two truths and a lie about your first job",
  "Tell two truths and a lie about things you have broken or lost",
  "Tell two truths and a lie about your celebrity encounters or sightings",
  "Tell two truths and a lie about your morning routine",
  "Tell two truths and a lie about things you have won or awards you got",
  "Tell two truths and a lie about your music taste",
  "Tell two truths and a lie about embarrassing moments",
  "Tell two truths and a lie about your hobbies",
  "Tell two truths and a lie about your pets — past or present",
  "Tell two truths and a lie about something that happened this year",
  "Tell two truths and a lie about your cooking abilities",
  "Tell two truths and a lie about your dreams or nightmares",
  "Tell two truths and a lie about your phone habits",
  "Tell two truths and a lie about things you have never done",
  "Tell two truths and a lie about your fashion choices",
  "Tell two truths and a lie about your best friend",
  "Tell two truths and a lie about your biggest regrets",
  "Tell two truths and a lie about languages or accents you can do",
  "Tell two truths and a lie about your exercise or sports history",
  "Tell two truths and a lie about the weirdest thing you own",
  "Tell two truths and a lie about your birthday celebrations",
  "Tell two truths and a lie about your driving or commute experiences",
  "Tell two truths and a lie about your movie and TV preferences",
  "Tell two truths and a lie about your high school years",
  "Tell two truths and a lie about things you believed as a kid",
  "Tell two truths and a lie about your shopping habits",
  "Tell two truths and a lie about your sleeping habits",
  "Tell two truths and a lie about your most memorable meal",
  "Tell two truths and a lie about your relationship with technology",
  "Tell two truths and a lie about a vacation gone wrong",
  "Tell two truths and a lie about your nicknames",
  "Tell two truths and a lie about books or shows that changed your mind about something",
  "Tell two truths and a lie about your fitness or health journey",
  "Tell two truths and a lie about your biggest achievements",
  "Tell two truths and a lie about your neighbors — past or present",
  "Tell two truths and a lie about your wedding or someone else's wedding you attended",
  "Tell two truths and a lie about your social media usage",
  "Tell two truths and a lie about your worst date or awkward encounter",
  "Tell two truths and a lie about gifts you have given or received",
  "Tell two truths and a lie about something nobody in this room knows about you",
  "Tell two truths and a lie about your weekend routine",
  "Tell two truths and a lie about your New Year's resolutions",
];
