export const wouldYouRatherDeck: string[] = [
  "Would you rather always have to sing instead of speak or always have to dance instead of walk?",
  "Would you rather be able to talk to animals or speak every human language fluently?",
  "Would you rather have unlimited free flights or unlimited free hotel stays?",
  "Would you rather live without music or live without movies?",
  "Would you rather always know when someone is lying or always get away with lying?",
  "Would you rather be famous but constantly followed by paparazzi or be unknown but completely free?",
  "Would you rather eat your favorite meal every day forever or never eat it again?",
  "Would you rather time travel to the past or to the future?",
  "Would you rather have the power of invisibility or the power of flight?",
  "Would you rather live in a treehouse or in a houseboat?",
  "Would you rather only be able to whisper or only be able to shout?",
  "Would you rather give up your phone for a month or give up your bed for a month?",
  "Would you rather always be 10 minutes late or always be 20 minutes early?",
  "Would you rather have a rewind button for your life or a pause button?",
  "Would you rather know how you die or know when you die?",
  "Would you rather be the funniest person in the room or the smartest?",
  "Would you rather lose the ability to read or the ability to speak?",
  "Would you rather have free Wi-Fi everywhere you go or free coffee everywhere you go?",
  "Would you rather be stuck in an elevator with your worst enemy or be stuck alone for 12 hours?",
  "Would you rather always have to tell the truth or always have to lie?",
  "Would you rather be able to breathe underwater or fly through the air?",
  "Would you rather win the lottery but have to share it with 100 strangers or find $10,000 that's all yours?",
  "Would you rather never be able to use social media again or never be able to watch TV again?",
  "Would you rather have a personal chef or a personal driver?",
  "Would you rather be the best player on a losing team or the worst player on a winning team?",
  "Would you rather live in a world with no problems or a world with no pain?",
  "Would you rather have the ability to read minds or see the future?",
  "Would you rather go without shampoo for the rest of your life or go without toothpaste?",
  "Would you rather be locked in a library overnight or locked in an amusement park overnight?",
  "Would you rather give up breakfast or give up dinner?",
  "Would you rather have a magic carpet or a see-through submarine?",
  "Would you rather never have homework again or never have to do chores again?",
  "Would you rather live somewhere it's always summer or somewhere it's always winter?",
  "Would you rather be able to control fire or control water?",
  "Would you rather always forget what you just said or always forget what you just heard?",
  "Would you rather have to wear wet socks forever or have a permanent pebble in your shoe?",
  "Would you rather be a famous musician or a famous inventor?",
  "Would you rather explore deep space or explore the deep ocean?",
  "Would you rather have a third arm or a third eye?",
  "Would you rather be able to teleport anywhere or be able to stop time?",
  "Would you rather eat only spicy food for a year or only bland food for a year?",
  "Would you rather never be able to go outside or never be able to go inside?",
  "Would you rather have a photographic memory or be able to forget anything on command?",
  "Would you rather be the host of a party or a guest at a party?",
  "Would you rather live without air conditioning or live without heating?",
  "Would you rather have a talking pet or a flying pet?",
  "Would you rather be the oldest sibling or the youngest sibling?",
  "Would you rather master every musical instrument or master every sport?",
  "Would you rather have one wish granted today or three wishes granted in ten years?",
  "Would you rather never feel cold again or never feel hot again?",
];
